on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.0b2
      - name: install virtualenv
        run: poetry install
      - name: run mypy
        run: poetry run mypy .
      - name: run black
        run: poetry run black .
      - name: run pytest
        run: poetry run py.test
